# Generated by Django 5.1.7 on 2025-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylink',
            name='source',
            field=models.CharField(default='', max_length=50),
        ),
    ]
