# Generated by Django 5.1.7 on 2025-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studylink_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylink',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('game', 'Game'), ('quiz', 'Quiz'), ('interactive', 'Interactive'), ('practice', 'Practice Problems')], default='text', max_length=20),
        ),
    ]
