# Generated by Django 5.1.7 on 2025-04-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studylink_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylink',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('practice', 'Practice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studylink',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studylink',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopic'),
        ),
    ]
