# Generated by Django 5.1.7 on 2025-04-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studylink_material_type_alter_studylink_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylink',
            name='question_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studylink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studylink',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('practice', 'Practice Problems')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studylink',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_links', to='core.subtopic'),
        ),
    ]
