# Generated by Django 5.1.7 on 2025-04-08 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studylink_question_identifier_studylink_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studylink',
            name='question_identifier',
        ),
        migrations.RemoveField(
            model_name='studylink',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='studylink',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('practice', 'Practice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studylink',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtopic'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
