# Generated by Django 5.1.7 on 2025-04-10 14:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='1-5 scale, 1 being easiest'),
        ),
        migrations.AddField(
            model_name='question',
            name='learning_preference',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive'), ('audio', 'Audio'), ('practice', 'Practice Problems')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='performance_metrics',
            field=models.JSONField(default=dict, help_text='JSON containing performance metrics for this question'),
        ),
        migrations.AddField(
            model_name='question',
            name='study_materials',
            field=models.JSONField(default=dict, help_text='JSON containing study materials for different learning preferences'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.avatar_path),
        ),
    ]
