# Generated by Django 5.1.7 on 2025-04-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subject_quizsession_practicesession_userresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='practice_session',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='quiz_session',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='learning_preference',
        ),
        migrations.RemoveField(
            model_name='question',
            name='performance_metrics',
        ),
        migrations.RemoveField(
            model_name='question',
            name='study_materials',
        ),
        migrations.CreateModel(
            name='SubjectQuizLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('last_attempt_date', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('weak_areas', models.JSONField(default=dict)),
                ('total_attempts', models.IntegerField(default=0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
            options={
                'verbose_name_plural': 'Subject Quiz Levels',
                'unique_together': {('student', 'subject', 'level')},
            },
        ),
        migrations.DeleteModel(
            name='PracticeSession',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
