# Generated by Django 5.1.7 on 2025-04-14 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_userresponse_practice_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('interactive', 'Interactive'), ('quiz', 'Quiz'), ('practice', 'Practice')], max_length=50)),
                ('score', models.FloatField(default=0.0)),
                ('is_weak_area', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.generaltopic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studylink')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subtopic')),
            ],
        ),
    ]
