# Generated by Django 5.1.7 on 2025-05-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_topic_name_alter_generaltopic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generaltopic',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
