# Generated by Django 5.1.7 on 2025-05-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_generaltopic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generaltopic',
            unique_together={('name', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('name', 'general_topic')},
        ),
    ]
