# Generated by Django 5.1.7 on 2025-05-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_schoolyear_question_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
