# Generated by Django 5.1.7 on 2025-05-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_level_subject_questiongenerationsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongenerationsetting',
            options={'verbose_name': 'Question Generation Setting', 'verbose_name_plural': 'Question Generation Settings'},
        ),
        migrations.AlterUniqueTogether(
            name='questiongenerationsetting',
            unique_together={('level',)},
        ),
        migrations.AlterField(
            model_name='questiongenerationsetting',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_settings', to='core.level'),
        ),
        migrations.RemoveField(
            model_name='questiongenerationsetting',
            name='subject',
        ),
    ]
