# Generated by Django 5.1.7 on 2025-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_questiongenerationsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
