# Generated by Django 5.1.7 on 2025-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_level_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_extension',
            field=models.CharField(blank=True, help_text='E.g., Jr., Sr., III, etc.', max_length=10),
        ),
    ]
