# Generated by Django 5.1.7 on 2025-05-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_questiongenerationsetting_passing_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='peu_control',
            field=models.IntegerField(default=0),
        ),
    ]
