# Generated by Django 5.1.7 on 2025-05-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_surveyresponse_peu_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('value', models.FloatField(help_text='Raw value (e.g., 0.92 for 92%)')),
                ('percentage', models.FloatField(help_text='Percentage value (e.g., 92 for 92%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
