# Generated by Django 5.1.7 on 2025-05-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_performancemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
